# cargo-deny configuration

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
]

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

vulnerability = "deny"
unmaintained = "warn"
unsound = "warn"
yanked = "warn"
notice = "warn"

ignore = [
    # Temporary ignores (remove after fixes)
]

[licenses]
version = 2
confidence-threshold = 0.8

allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

deny = [
    "GPL-2.0",
    "GPL-3.0", 
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
]

copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

allow = [
    # Allow multiple versions of these crates
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]

deny = [
    # Security-sensitive: deny known vulnerable crates
    { name = "openssl", version = "<0.10.55", reason = "Security vulnerabilities in older versions" },
    { name = "reqwest", version = "<0.11.18", reason = "Security vulnerabilities" },
    { name = "tokio", version = "<1.28.0", reason = "Security vulnerabilities" },
    { name = "hyper", version = "<0.14.27", reason = "Security vulnerabilities" },
]

skip = [
    # Dependencies with known issues we accept
]

skip-tree = [
    # Skip entire dependency trees
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []